# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "55991fbf3a57c1a93bb111362a56a45f"
name = "Approvefy"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/webhooks/customers_create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,write_customers,write_app_proxy,read_locales"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://example.com/api"
subpath = "customer-approval"
prefix = "apps"
